
DROP DATABASE IF EXISTS pta_home;

CREATE DATABASE IF NOT EXISTS pta_home
		DEFAULT CHARACTER SET utf8
		COLLATE utf8_unicode_ci;

CREATE USER 'pta_home'@'%' IDENTIFIED BY '123456';

GRANT USAGE ON * . * TO 'pta_home'@'%'
		IDENTIFIED BY '123456'
		WITH MAX_QUERIES_PER_HOUR 0
		MAX_CONNECTIONS_PER_HOUR 0
		MAX_UPDATES_PER_HOUR 0
		MAX_USER_CONNECTIONS 0;

GRANT ALL PRIVILEGES ON pta_home . * TO 'pta_home'@'%';
