
CREATE USER 'pta_home'@'localhost' IDENTIFIED BY '123456';

GRANT USAGE ON * . * TO 'pta_home'@'localhost' IDENTIFIED BY '123456' WITH MAX_QUERIES_PER_HOUR 0 MAX_CONNECTIONS_PER_HOUR 0 MAX_UPDATES_PER_HOUR 0 MAX_USER_CONNECTIONS 0 ;

CREATE DATABASE IF NOT EXISTS `pta_home` ;

GRANT ALL PRIVILEGES ON `pta_home` . * TO 'pta_home'@'localhost';
